import { IMAGE_IDS } from "shared/features/ids/images";

export const DEATH_PARTICLE_PROPS: Partial<WritableInstanceProperties<ParticleEmitter>> = {
    Brightness: 4.455,
    Color: new ColorSequence([
        new ColorSequenceKeypoint(0, new Color3(1, 0, 0)),
        new ColorSequenceKeypoint(0.1, new Color3(0, 0, 0)),
        new ColorSequenceKeypoint(0.2, new Color3(1, 0, 0)),
        new ColorSequenceKeypoint(0.3, new Color3(0, 0, 0)),
        new ColorSequenceKeypoint(0.4, new Color3(1, 0, 0)),
        new ColorSequenceKeypoint(0.5, new Color3(0, 0, 0)),
        new ColorSequenceKeypoint(0.6, new Color3(1, 0, 0)),
        new ColorSequenceKeypoint(0.7, new Color3(0, 0, 0)),
        new ColorSequenceKeypoint(0.8, new Color3(1, 0, 0)),
        new ColorSequenceKeypoint(0.9, new Color3(0, 0, 0)),
        new ColorSequenceKeypoint(1, new Color3(1, 0, 0)),
    ]),
    LightEmission: 0.45,
    LightInfluence: 0,
    Orientation: Enum.ParticleOrientation.FacingCamera,
    Size: new NumberSequence(1, 0),
    Squash: new NumberSequence(1, 1),
    Texture: IMAGE_IDS.deathChinese,
    Transparency: new NumberSequence(0, 1),
    ZOffset: 0.5,
    EmissionDirection: Enum.NormalId.Top,
    Enabled: true,
    Lifetime: new NumberRange(3.5),
    Rate: 21,
    Rotation: new NumberRange(30),
    RotSpeed: new NumberRange(220),
    Speed: new NumberRange(29),
    SpreadAngle: new Vector2(1000, 1000),
    Shape: Enum.ParticleEmitterShape.Sphere,
    ShapeInOut: Enum.ParticleEmitterShapeInOut.Outward,
    ShapePartial: 1,
    ShapeStyle: Enum.ParticleEmitterShapeStyle.Volume,
    Acceleration: new Vector3(1, 1, 1),
    Drag: 2.5,
    TimeScale: 1,
    VelocityInheritance: 0,
    LockedToPart: false,
    WindAffectsDrag: true,
};
