import { Material } from "type";

type Catergory = "grass" | "mud" | "wood" | "stone";

export const MATERIAL_CATEGORIES: Map<Material, Catergory> = new Map([
    ["Air", "grass"],
    ["Aluminum", "stone"],
    ["Asphalt", "stone"],
    ["Basalt", "stone"],
    ["Brick", "stone"],
    ["Cardboard", "wood"],
    ["Carpet", "grass"],
    ["CeramicTiles", "stone"],
    ["ClayRoofTiles", "stone"],
    ["Cobblestone", "stone"],
    ["Concrete", "stone"],
    ["CorrodedMetal", "stone"],
    ["CrackedLava", "stone"],
    ["DiamondPlate", "stone"],
    ["Fabric", "grass"],
    ["Foil", "grass"],
    ["ForceField", "stone"],
    ["Glacier", "stone"],
    ["Glass", "stone"],
    ["Granite", "stone"],
    ["Grass", "grass"],
    ["Ground", "stone"],
    ["Ice", "stone"],
    ["LeafyGrass", "grass"],
    ["Leather", "grass"],
    ["Limestone", "stone"],
    ["Marble", "stone"],
    ["Metal", "stone"],
    ["Mud", "mud"],
    ["Neon", "stone"],
    ["Pavement", "stone"],
    ["Pebble", "stone"],
    ["Plaster", "stone"],
    ["Plastic", "stone"],
    ["Rock", "stone"],
    ["RoofShingles", "stone"],
    ["Rubber", "stone"],
    ["Salt", "stone"],
    ["Sand", "grass"],
    ["Sandstone", "stone"],
    ["Slate", "stone"],
    ["SmoothPlastic", "stone"],
    ["Snow", "mud"],
    ["Water", "grass"],
    ["Wood", "wood"],
    ["WoodPlanks", "wood"],
]);

export const PLACEHOLDER_CATERORY: Catergory = "stone";
